// apps/api/src/controllers/export.controller.ts

import { Request, Response } from 'express';
import { prisma } from '../lib/prisma';
import { generateExecutiveExport } from '../services/pdf.service';

export const handleExecutiveExport = async (req: Request, res: Response) => {
  const { organizationId } = req.params;

  // 1. Fetch the Live Signals
  const documents = await prisma.document.findMany({
    where: { organizationId },
    orderBy: { expiryDate: 'asc' }
  });

  // 2. Construct the "Story" Template
  // We mirror the CSS from our 'styles.css' to ensure fidelity
  const htmlTemplate = `
    <html>
      <head>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;500;700&display=swap');
          body { font-family: 'Space Grotesk', sans-serif; background: #f8fafc; }
        </style>
      </head>
      <body class="p-10">
        <div class="flex justify-between items-center mb-10 border-b pb-6">
          <h1 class="text-4xl font-black tracking-tighter uppercase">Administrative Continuity Report</h1>
          <div class="text-right">
            <p class="text-xs font-bold opacity-50">GENERATED BY V-AXIS</p>
            <p class="text-sm font-black">${new Date().toLocaleDateString()}</p>
          </div>
        </div>
        
        <div class="space-y-4">
          ${documents.map(doc => `
            <div class="flex justify-between items-center p-4 border rounded-2xl">
              <div>
                <p class="text-xs font-black uppercase opacity-40">${doc.type}</p>
                <p class="font-bold text-lg">${doc.personName || doc.entityName}</p>
              </div>
              <div class="text-right">
                <p class="text-[10px] font-black opacity-40 uppercase">Expiry Status</p>
                <p class="font-bold ${doc.status === 'ACTIVE' ? 'text-emerald-600' : 'text-rose-600'}">
                  ${doc.expiryDate.toDateString()}
                </p>
              </div>
            </div>
          `).join('')}
        </div>
      </body>
    </html>
  `;

  // 3. Trigger the Bridge
  const pdfBuffer = await generateExecutiveExport(htmlTemplate);

  res.set({
    'Content-Type': 'application/pdf',
    'Content-Disposition': `attachment; filename=VAXIS_Executive_Report.pdf`,
  });
  
  res.send(pdfBuffer);
};