import type { FastifyReply, FastifyRequest } from "fastify";
import { asc } from "drizzle-orm";

import { db } from "@vaxis/db";
import { documents } from "@vaxis/db/schema";

import { generateExecutiveExport } from "../services/pdf.service";

type ExportParams = {
  organizationId: string;
};

export const handleExecutiveExport = async (
  request: FastifyRequest<{ Params: ExportParams }>,
  reply: FastifyReply,
) => {
  const { organizationId } = request.params;

  const documentRows = await db
    .select()
    .from(documents)
    .orderBy(asc(documents.expiryDate))
    .limit(100);

  const htmlTemplate = `
    <html>
      <head>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;500;700&display=swap');
          body { font-family: 'Inter', sans-serif; background: #f8fafc; color: #0f172a; }
        </style>
      </head>
      <body class="p-10">
        <div class="mb-10 flex items-center justify-between border-b pb-6">
          <div>
            <h1 class="text-4xl font-black tracking-tight">Administrative Continuity Report</h1>
            <p class="mt-2 text-xs font-semibold uppercase tracking-[0.2em] text-emerald-600">
              Organization ${organizationId}
            </p>
          </div>
          <div class="text-right">
            <p class="text-xs font-bold opacity-50">Generated by V-AXIS</p>
            <p class="text-sm font-black">${new Date().toLocaleDateString()}</p>
          </div>
        </div>
        <div class="space-y-4">
          ${documentRows
            .map((document) => {
              const title = document.title || "Untitled record";
              const statusColor =
                document.status === "ACTIVE" ? "text-emerald-600" : "text-rose-600";
              const expiryDate = document.expiryDate
                ? new Date(document.expiryDate).toDateString()
                : "No expiry date";

              return `
                <div class="flex items-center justify-between rounded-2xl border p-4">
                  <div>
                    <p class="text-xs font-black uppercase opacity-40">${document.dnaCode}</p>
                    <p class="text-lg font-bold">${title}</p>
                  </div>
                  <div class="text-right">
                    <p class="text-[10px] font-black uppercase opacity-40">Expiry Status</p>
                    <p class="font-bold ${statusColor}">${expiryDate}</p>
                  </div>
                </div>
              `;
            })
            .join("")}
        </div>
      </body>
    </html>
  `;

  const pdfBuffer = await generateExecutiveExport(htmlTemplate);

  reply.header("Content-Type", "application/pdf");
  reply.header(
    "Content-Disposition",
    'attachment; filename="VAXIS_Executive_Report.pdf"',
  );

  return reply.send(pdfBuffer);
};
